// File generated by FlutterFire CLI.
// Ignore this file for now - Firebase configuration will be added later
// when Firebase project is set up.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

/// Default FirebaseOptions for current platform.
///
/// TODO: Replace with actual Firebase configuration when setting up Firebase project
/// 1. Create a Firebase project at https://console.firebase.google.com
/// 2. Add Android app with package name: com.example.happyco
/// 3. Add iOS app with bundle ID: com.example.happyco
/// 4. Copy the configuration here
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    // Stub configuration - replace with actual Firebase config
    return const FirebaseOptions(
      apiKey: 'STUB_API_KEY',
      appId: 'STUB_APP_ID',
      messagingSenderId: 'STUB_SENDER_ID',
      projectId: 'stub-project-id',
    );
  }
}
